image:
- Visual Studio 2015
- ubuntu1804

cache:
  - '%LOCALAPPDATA%\pip\Cache'

build: off

environment:

  global:
      #PLATFORMTOOLSET: "v140"
    NUMPY_HEAD: https://github.com/numpy/numpy.git
    NUMPY_BRANCH: master 
    MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
  #PY_DIR: C:\Python36-x64


  matrix:
    # - PYTHON: "C:\\Python36"
    #   PYTHON_VERSION: "3.6.x" # currently 3.6.5
    #   PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.7" # currently 3.6.5
      PYTHON_ARCH: "64"

    #- PYTHON: "C:\\Python37-x64"
      #PYTHON_VERSION: "3.7.1" # currently 3.6.5
      #PYTHON_ARCH: "64"

clone_depth: 3

stack: python %PYTHON_VERSION%

init:

- cmd: set PATH=%MINGW_DIR%;%PATH%
- cmd: set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
# Replace numpy distutils with a version that can build with msvc + mingw-gfortran
- pip install -U pip setuptools wheel
- pip install --quiet -U --upgrade wheel
- pip install --quiet -r requirements.txt
- ps: |
      $NumpyDir = $((python -c 'import os; import numpy; print(os.path.dirname(numpy.__file__))') | Out-String).Trim()
      rm -r -Force "$NumpyDir\distutils"
      $tmpdir = New-TemporaryFile | %{ rm $_; mkdir $_ }
      echo $env:NUMPY_HEAD
      echo $env:NUMPY_BRANCH
      git clone -q --depth=1 -b $env:NUMPY_BRANCH $env:NUMPY_HEAD $tmpdir
      mv $tmpdir\numpy\distutils $NumpyDir
install:
    #- "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

- cmd: "set PATH=%MINGW_DIR%;%PATH%"
- cmd: "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
#- sh: "sudo apt-get install libgfortran3"
#- sh: "gfortran --version"
- mkdir dist
- pip wheel --no-build-isolation --wheel-dir=dist .
  #- cmd: bash prepare_pyinstall.sh
  #- cmd: "python setup.py bdist_wininst"
 

test_script:
 - echo PUT TEST SCRIPTS HERE  

after_test:
  # - cmd: "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"
  # - cmd: "%PYTHON%\\python.exe setup.py bdist_wheel"
  # - sh: "python3 setup.py bdist_wheel"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*


