image:
    #- Visual Studio 2017
- Ubuntu

  #stack: python 3.6

build: off

environment:
    #APPVEYOR_SAVE_CACHE_ON_ERROR: true

  MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
  #PY_DIR: C:\Python36-x64


  matrix:
    # - PYTHON: "C:\\Python36"
    #   PYTHON_VERSION: "3.6.x" # currently 3.6.5
    #   PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36-x64"
      #- PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x" # currently 3.6.5
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python37-x64"
      #- PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.7.x" # currently 3.6.5
      PYTHON_ARCH: "64"

clone_depth: 3

stack: python %PYTHON_VERSION%

init:
- cmd: set PATH=%MINGW_DIR%;%PATH%
- cmd: set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

install:
    #- "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

- cmd: "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
- sh: "export PYTHONPATH=$PYTHON"
- pip install -U numpy
- pip install -U wheel
- pip install --quiet -r requirements.txt
- echo Starting to compile
- cd arpessimist/fortran_routines
- cmd: sh compile_windows.sh
- sh: ./compile.sh
- echo Compilation finished!
- cd ../../
- sh: "python3 setup.py bdist_wheel --plat-name=manylinux1_x86_64"
- sh: "python3 rename_version.py"
- cmd: "python setup.py bdist_wheel --plat-name=win_amd64 " # Readd sdist later
- cmd: "python rename_version.py"
  #- cmd: "python setup.py bdist_wininst"

test_script:
 - echo PUT TEST SCRIPTS HERE  

after_test:
  # - cmd: "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"
  # - cmd: "%PYTHON%\\python.exe setup.py bdist_wheel"
  # - sh: "python3 setup.py bdist_wheel"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*


