image:
    #- Visual Studio 2017
- Ubuntu

stack: python 3

build: off

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

  MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
  PY_DIR: C:\Python37-x64


  matrix:
    # - PYTHON: "C:\\Python36"
    #   PYTHON_VERSION: "3.6.x" # currently 3.6.5
    #   PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36-x64"
      #- PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x" # currently 3.6.5
      PYTHON_ARCH: "64"

clone_depth: 3

init:
- cmd: set PATH=%MINGW_DIR%;%PATH%
  #- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

install:
- cmd: "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
- pip install -U numpy
- pip install -U wheel
- pip install --quiet -r requirements.txt
- echo Starting to compile
- cd arpessimist/fortran_routines
- cmd: sh compile_windows.sh
- sh: ./compile.sh
- echo Compilation finished!
- cd ../../
- sh: "python3 setup.py sdist bdist_wheel --plat-name=manylinux_x86_64"
- cmd: "python setup.py sdist bdist_wheel --plat-name=win_amd64 "
  #- cmd: "python setup.py bdist_wininst"

test_script:
 - echo PUT TEST SCRIPTS HERE  

after_test:
  # - cmd: "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"
  # - cmd: "%PYTHON%\\python.exe setup.py bdist_wheel"
  # - sh: "python3 setup.py bdist_wheel"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*


